/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cceProject;

import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author shahriar
 */
public class CoverTeacher extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement pst =null;
    ResultSet rs= null;

    /**
     * Creates new form CoverTeacher
     */
    public CoverTeacher() {
        initComponents();
        conn = connection.connectDB();
        viewTable();
    }
 private void viewTable(){
        String sql="select * from CR";
        try {
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            crtable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
 private void clear(){
     usrbox.setText(null);
     passbox.setText(null);
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatecr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        crtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usrbox = new javax.swing.JTextField();
        passbox = new javax.swing.JTextField();
        addcr = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updatecr.setBackground(new java.awt.Color(204, 204, 0));
        updatecr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatecr.setText("UpdateCR");
        updatecr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecrActionPerformed(evt);
            }
        });
        getContentPane().add(updatecr, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 214, -1, -1));

        crtable.setBackground(new java.awt.Color(204, 255, 204));
        crtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        crtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crtableMouseClicked(evt);
            }
        });
        crtable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                crtableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(crtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 39, 222, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Username");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Password");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 51), 3, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        usrbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrboxActionPerformed(evt);
            }
        });
        getContentPane().add(usrbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 104, -1));
        getContentPane().add(passbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 104, -1));

        addcr.setBackground(new java.awt.Color(0, 153, 0));
        addcr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addcr.setText("AddCR");
        addcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcrActionPerformed(evt);
            }
        });
        getContentPane().add(addcr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("DeleteCR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 214, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cceProject/logos/shaheed.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatecrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecrActionPerformed
       int row=crtable.getSelectedRow();
       String selection =crtable.getModel().getValueAt(row, 0).toString();
        String sql="update CR set"
        + " user='"+usrbox.getText()+"',"
        + " pass='"+passbox.getText()+"'"
        +"where id ="+selection;
        try {
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Updated");
            viewTable();
            clear();
             pst.close();
             rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updatecrActionPerformed

    private void addcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcrActionPerformed
        String sql="insert into CR (user,pass)values(?,?)";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1,usrbox.getText());
            pst.setString(2,passbox.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"added new CR");
            viewTable();
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addcrActionPerformed

    private void crtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crtableMouseClicked
       int row=crtable.getSelectedRow();
       String selection =crtable.getModel().getValueAt(row, 0).toString();
        String sql="select * from CR where id="+selection;
        try {
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                usrbox.setText(rs.getString("user"));
                passbox.setText(rs.getString("pass"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_crtableMouseClicked

    private void crtableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crtableKeyReleased
        int row=crtable.getSelectedRow();
       String selection =crtable.getModel().getValueAt(row, 0).toString();
        String sql="select * from CR where id="+selection;
        try {
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                usrbox.setText(rs.getString("user"));
                passbox.setText(rs.getString("pass"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_crtableKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a = JOptionPane.showConfirmDialog((Component)null,"sure to delete?","DELETE",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){
        int row = crtable.getSelectedRow();
        String cell = crtable.getModel().getValueAt(row, 0).toString();
        String sql="delete from CR where id ="+cell;
        try {
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Deleted Successfully");
            viewTable();
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
            }
            
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usrboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new CoverMain().setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoverTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoverTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoverTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoverTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoverTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcr;
    private javax.swing.JTable crtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField passbox;
    private javax.swing.JButton updatecr;
    private javax.swing.JTextField usrbox;
    // End of variables declaration//GEN-END:variables
}
