/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cceProject;

import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author shahriar
 */
public class viewInfo extends javax.swing.JFrame {
 Connection conn=null;
   PreparedStatement pst =null;
   ResultSet rs= null;
    /**
     * Creates new form viewInfo
     */
    public viewInfo() {
         initComponents();
        conn = connection.connectDB();
        updateCombo();
    }
    
    
    private void updateCombo(){
        String sql="select * from Student";
        try {
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                com1.addItem(rs.getString("id"));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        com1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        viewname = new javax.swing.JTextField();
        viewid = new javax.swing.JTextField();
        viewreg = new javax.swing.JTextField();
        viewnick = new javax.swing.JTextField();
        viewemail = new javax.swing.JTextField();
        viewphone = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Student Informations");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 31, 314, 47));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select Student ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 116, 134, 37));

        com1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        com1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID" }));
        com1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        com1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                com1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        com1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com1ActionPerformed(evt);
            }
        });
        getContentPane().add(com1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 172, 37));

        jLabel3.setBackground(new java.awt.Color(255, 255, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NAME:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 192, 76, 25));

        jLabel4.setBackground(new java.awt.Color(255, 255, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ID:");
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 235, 76, 25));

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("REG:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 278, 76, 28));

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("NICK:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 317, 76, 27));

        jLabel7.setBackground(new java.awt.Color(255, 255, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("EMAIL:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 355, 76, 26));

        jLabel8.setBackground(new java.awt.Color(255, 255, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("PHONE:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 76, 28));

        viewname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewnameActionPerformed(evt);
            }
        });
        getContentPane().add(viewname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 220, 25));

        viewid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewidActionPerformed(evt);
            }
        });
        getContentPane().add(viewid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 220, 25));
        getContentPane().add(viewreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 278, 220, 28));

        viewnick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewnickActionPerformed(evt);
            }
        });
        getContentPane().add(viewnick, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 317, 220, 27));

        viewemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewemailActionPerformed(evt);
            }
        });
        getContentPane().add(viewemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 355, 220, 26));

        viewphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewphoneActionPerformed(evt);
            }
        });
        getContentPane().add(viewphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 396, 220, 28));

        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 435, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 70, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cceProject/logos/plane.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void com1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com1ActionPerformed

    private void viewphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewphoneActionPerformed

    private void viewemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewemailActionPerformed

    private void viewnickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewnickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewnickActionPerformed

    private void viewnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewnameActionPerformed

    private void viewidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewidActionPerformed

    private void com1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_com1PopupMenuWillBecomeInvisible
       String item=com1.getSelectedItem().toString();
       String sql="select * from Student where id =?";
       
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, item);
            rs = pst.executeQuery();
            if(rs.next()){
                
                
                viewname.setText(rs.getString("name"));
                viewid.setText(rs.getString("id"));
                viewreg.setText(rs.getString("reg"));
                viewnick.setText(rs.getString("nick"));
                viewemail.setText(rs.getString("email"));
                viewphone.setText(rs.getString("phone"));
                
                
            }
            
        } catch (Exception e) {
        }
     
           
           
    }//GEN-LAST:event_com1PopupMenuWillBecomeInvisible

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
     String sql ="update Student set "
             + "name ='"+viewname.getText()+"',"
             + "reg ='"+viewreg.getText()+"',"
             + "nick ='"+viewnick.getText()+"',"
             + "email ='"+viewemail.getText()+"',"
             + "phone ='"+viewphone.getText()+"'"
             + "where id = "+com1.getSelectedItem().toString();
        try {
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Updated Successfully");
             pst.close();
             rs.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            
    }//GEN-LAST:event_updatebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new coverCR().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField viewemail;
    private javax.swing.JTextField viewid;
    private javax.swing.JTextField viewname;
    private javax.swing.JTextField viewnick;
    private javax.swing.JTextField viewphone;
    private javax.swing.JTextField viewreg;
    // End of variables declaration//GEN-END:variables
}
